#version: 1.0.3
#description: UPF initial local configuration

# The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
#pfcp:
#  addr: 127.0.0.8   # IP addr for listening
#  nodeID: 127.0.0.8 # External IP or FQDN can be reached
#  retransTimeout: 1s # retransmission timeout
#  maxRetrans: 3 # the max number of retransmission

#gtpu:
#  forwarder: gtp5g
  # forwarder: p4gtp5g
  # The IP list of the N3/N9 interfaces on this UPF
  # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
#  ifList:
#    - addr: 192.168.1.47
#      type: N3
      # name: upf.5gc.nctu.me
      # ifname: gtpif

# The DNN list supported by UPF
#dnnList:
#  - dnn: internet # Data Network Name
#    cidr: 10.60.0.0/24 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
    # natifname: eth0

#logger: # log output setting
#  enable: true # true or false
#  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
#  reportCaller: false # enable the caller report or not, value: true or false
version: 1.0.3
description: UPF initial local configuration

# The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
pfcp:
  addr: 127.0.0.8   # IP addr for listening
  nodeID: 127.0.0.8 # External IP or FQDN can be reached
  retransTimeout: 1s # retransmission timeout
  maxRetrans: 3 # the max number of retransmission

gnb:
  addr: 192.168.10.3
  mac: 00:0c:29:62:45:fd

upfc:
  grpc: 192.168.1.56:50021

gtpu:
  forwarder: p4gtp5g
  # forwarder: p4gtp5g
  # The IP list of the N3/N9 interfaces on this UPF
  # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
  ifList:
    - addr: 192.168.10.2
      type: N3
      Mac: 00:0c:29:a4:93:14

      portNumber: 64
      # name: upf.5gc.nctu.me
      # ifname: gtpif
    - addr: 192.168.10.3
      type: N6
      Mac: 00:0c:29:62:45:fd
      portNumber: 65


# The DNN list supported by UPF
dnnList:
  - dnn: internet # Data Network Name
    cidr: 10.60.0.0/24 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
    mac:  00:0c:29:a4:93:14
    addr: 192.168.1.57
    # natifname: eth0

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
