// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: grpc.proto

package forwarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SrcIfLookupTableData_ActionName int32

const (
	SrcIfLookupTableData_set_source_iface SrcIfLookupTableData_ActionName = 0
)

// Enum value maps for SrcIfLookupTableData_ActionName.
var (
	SrcIfLookupTableData_ActionName_name = map[int32]string{
		0: "set_source_iface",
	}
	SrcIfLookupTableData_ActionName_value = map[string]int32{
		"set_source_iface": 0,
	}
)

func (x SrcIfLookupTableData_ActionName) Enum() *SrcIfLookupTableData_ActionName {
	p := new(SrcIfLookupTableData_ActionName)
	*p = x
	return p
}

func (x SrcIfLookupTableData_ActionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SrcIfLookupTableData_ActionName) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[0].Descriptor()
}

func (SrcIfLookupTableData_ActionName) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[0]
}

func (x SrcIfLookupTableData_ActionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SrcIfLookupTableData_ActionName.Descriptor instead.
func (SrcIfLookupTableData_ActionName) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3, 0}
}

type MyStationTableData_ActionName int32

const (
	MyStationTableData_no_action MyStationTableData_ActionName = 0
)

// Enum value maps for MyStationTableData_ActionName.
var (
	MyStationTableData_ActionName_name = map[int32]string{
		0: "no_action",
	}
	MyStationTableData_ActionName_value = map[string]int32{
		"no_action": 0,
	}
)

func (x MyStationTableData_ActionName) Enum() *MyStationTableData_ActionName {
	p := new(MyStationTableData_ActionName)
	*p = x
	return p
}

func (x MyStationTableData_ActionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyStationTableData_ActionName) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[1].Descriptor()
}

func (MyStationTableData_ActionName) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[1]
}

func (x MyStationTableData_ActionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyStationTableData_ActionName.Descriptor instead.
func (MyStationTableData_ActionName) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{6, 0}
}

type RouteTableData_ActionName int32

const (
	RouteTableData_route RouteTableData_ActionName = 0
)

// Enum value maps for RouteTableData_ActionName.
var (
	RouteTableData_ActionName_name = map[int32]string{
		0: "route",
	}
	RouteTableData_ActionName_value = map[string]int32{
		"route": 0,
	}
)

func (x RouteTableData_ActionName) Enum() *RouteTableData_ActionName {
	p := new(RouteTableData_ActionName)
	*p = x
	return p
}

func (x RouteTableData_ActionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteTableData_ActionName) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[2].Descriptor()
}

func (RouteTableData_ActionName) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[2]
}

func (x RouteTableData_ActionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteTableData_ActionName.Descriptor instead.
func (RouteTableData_ActionName) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{9, 0}
}

type PDRTableData_ActionName int32

const (
	PDRTableData_set_pdr_attributes     PDRTableData_ActionName = 0
	PDRTableData_set_pdr_attributes_qos PDRTableData_ActionName = 1
)

// Enum value maps for PDRTableData_ActionName.
var (
	PDRTableData_ActionName_name = map[int32]string{
		0: "set_pdr_attributes",
		1: "set_pdr_attributes_qos",
	}
	PDRTableData_ActionName_value = map[string]int32{
		"set_pdr_attributes":     0,
		"set_pdr_attributes_qos": 1,
	}
)

func (x PDRTableData_ActionName) Enum() *PDRTableData_ActionName {
	p := new(PDRTableData_ActionName)
	*p = x
	return p
}

func (x PDRTableData_ActionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PDRTableData_ActionName) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[3].Descriptor()
}

func (PDRTableData_ActionName) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[3]
}

func (x PDRTableData_ActionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PDRTableData_ActionName.Descriptor instead.
func (PDRTableData_ActionName) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{12, 0}
}

type FARTableData_ActionName int32

const (
	FARTableData_load_normal_far_attributes FARTableData_ActionName = 0
	FARTableData_load_tunnel_far_attributes FARTableData_ActionName = 1
)

// Enum value maps for FARTableData_ActionName.
var (
	FARTableData_ActionName_name = map[int32]string{
		0: "load_normal_far_attributes",
		1: "load_tunnel_far_attributes",
	}
	FARTableData_ActionName_value = map[string]int32{
		"load_normal_far_attributes": 0,
		"load_tunnel_far_attributes": 1,
	}
)

func (x FARTableData_ActionName) Enum() *FARTableData_ActionName {
	p := new(FARTableData_ActionName)
	*p = x
	return p
}

func (x FARTableData_ActionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FARTableData_ActionName) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_enumTypes[4].Descriptor()
}

func (FARTableData_ActionName) Type() protoreflect.EnumType {
	return &file_grpc_proto_enumTypes[4]
}

func (x FARTableData_ActionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FARTableData_ActionName.Descriptor instead.
func (FARTableData_ActionName) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{15, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

//-----------
type SrcIfLookupTableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstAddr          string `protobuf:"bytes,1,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	DstAddrPrefixLen uint32 `protobuf:"varint,2,opt,name=dst_addr_prefix_len,json=dstAddrPrefixLen,proto3" json:"dst_addr_prefix_len,omitempty"`
}

func (x *SrcIfLookupTableKey) Reset() {
	*x = SrcIfLookupTableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrcIfLookupTableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrcIfLookupTableKey) ProtoMessage() {}

func (x *SrcIfLookupTableKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrcIfLookupTableKey.ProtoReflect.Descriptor instead.
func (*SrcIfLookupTableKey) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *SrcIfLookupTableKey) GetDstAddr() string {
	if x != nil {
		return x.DstAddr
	}
	return ""
}

func (x *SrcIfLookupTableKey) GetDstAddrPrefixLen() uint32 {
	if x != nil {
		return x.DstAddrPrefixLen
	}
	return 0
}

type SrcIfLookupTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action              SrcIfLookupTableData_ActionName            `protobuf:"varint,1,opt,name=action,proto3,enum=SrcIfLookupTableData_ActionName" json:"action,omitempty"`
	SrcIfLookupAction_1 *SrcIfLookupTableData_ActionSetSourceIface `protobuf:"bytes,2,opt,name=SrcIfLookup_action_1,json=SrcIfLookupAction1,proto3" json:"SrcIfLookup_action_1,omitempty"`
}

func (x *SrcIfLookupTableData) Reset() {
	*x = SrcIfLookupTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrcIfLookupTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrcIfLookupTableData) ProtoMessage() {}

func (x *SrcIfLookupTableData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrcIfLookupTableData.ProtoReflect.Descriptor instead.
func (*SrcIfLookupTableData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *SrcIfLookupTableData) GetAction() SrcIfLookupTableData_ActionName {
	if x != nil {
		return x.Action
	}
	return SrcIfLookupTableData_set_source_iface
}

func (x *SrcIfLookupTableData) GetSrcIfLookupAction_1() *SrcIfLookupTableData_ActionSetSourceIface {
	if x != nil {
		return x.SrcIfLookupAction_1
	}
	return nil
}

type CreateSrcIfLookTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *SrcIfLookupTableKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data *SrcIfLookupTableData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateSrcIfLookTableRequest) Reset() {
	*x = CreateSrcIfLookTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSrcIfLookTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSrcIfLookTableRequest) ProtoMessage() {}

func (x *CreateSrcIfLookTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSrcIfLookTableRequest.ProtoReflect.Descriptor instead.
func (*CreateSrcIfLookTableRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSrcIfLookTableRequest) GetKey() *SrcIfLookupTableKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateSrcIfLookTableRequest) GetData() *SrcIfLookupTableData {
	if x != nil {
		return x.Data
	}
	return nil
}

// -------------------
type MyStationTableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstMac string `protobuf:"bytes,1,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
}

func (x *MyStationTableKey) Reset() {
	*x = MyStationTableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStationTableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStationTableKey) ProtoMessage() {}

func (x *MyStationTableKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStationTableKey.ProtoReflect.Descriptor instead.
func (*MyStationTableKey) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *MyStationTableKey) GetDstMac() string {
	if x != nil {
		return x.DstMac
	}
	return ""
}

type MyStationTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action MyStationTableData_ActionName `protobuf:"varint,1,opt,name=action,proto3,enum=MyStationTableData_ActionName" json:"action,omitempty"`
}

func (x *MyStationTableData) Reset() {
	*x = MyStationTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStationTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStationTableData) ProtoMessage() {}

func (x *MyStationTableData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStationTableData.ProtoReflect.Descriptor instead.
func (*MyStationTableData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *MyStationTableData) GetAction() MyStationTableData_ActionName {
	if x != nil {
		return x.Action
	}
	return MyStationTableData_no_action
}

type CreateMyStationTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *MyStationTableKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // NoAction
	Data *MyStationTableData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateMyStationTableRequest) Reset() {
	*x = CreateMyStationTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMyStationTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMyStationTableRequest) ProtoMessage() {}

func (x *CreateMyStationTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMyStationTableRequest.ProtoReflect.Descriptor instead.
func (*CreateMyStationTableRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMyStationTableRequest) GetKey() *MyStationTableKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateMyStationTableRequest) GetData() *MyStationTableData {
	if x != nil {
		return x.Data
	}
	return nil
}

// ---------------------
type RouteTableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextHopIp          string `protobuf:"bytes,1,opt,name=next_hop_ip,json=nextHopIp,proto3" json:"next_hop_ip,omitempty"`
	NextHopIpPrefixLen uint32 `protobuf:"varint,2,opt,name=next_hop_ip_prefix_len,json=nextHopIpPrefixLen,proto3" json:"next_hop_ip_prefix_len,omitempty"`
}

func (x *RouteTableKey) Reset() {
	*x = RouteTableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteTableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableKey) ProtoMessage() {}

func (x *RouteTableKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableKey.ProtoReflect.Descriptor instead.
func (*RouteTableKey) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *RouteTableKey) GetNextHopIp() string {
	if x != nil {
		return x.NextHopIp
	}
	return ""
}

func (x *RouteTableKey) GetNextHopIpPrefixLen() uint32 {
	if x != nil {
		return x.NextHopIpPrefixLen
	}
	return 0
}

type RouteTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action        RouteTableData_ActionName   `protobuf:"varint,1,opt,name=action,proto3,enum=RouteTableData_ActionName" json:"action,omitempty"`
	RouteAction_1 *RouteTableData_ActionRoute `protobuf:"bytes,2,opt,name=route_action_1,json=routeAction1,proto3" json:"route_action_1,omitempty"`
}

func (x *RouteTableData) Reset() {
	*x = RouteTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableData) ProtoMessage() {}

func (x *RouteTableData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableData.ProtoReflect.Descriptor instead.
func (*RouteTableData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *RouteTableData) GetAction() RouteTableData_ActionName {
	if x != nil {
		return x.Action
	}
	return RouteTableData_route
}

func (x *RouteTableData) GetRouteAction_1() *RouteTableData_ActionRoute {
	if x != nil {
		return x.RouteAction_1
	}
	return nil
}

type CreateRouteTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *RouteTableKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data *RouteTableData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateRouteTableRequest) Reset() {
	*x = CreateRouteTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteTableRequest) ProtoMessage() {}

func (x *CreateRouteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteTableRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteTableRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRouteTableRequest) GetKey() *RouteTableKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateRouteTableRequest) GetData() *RouteTableData {
	if x != nil {
		return x.Data
	}
	return nil
}

// ------------------
type PDRTableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcIface          uint32 `protobuf:"varint,1,opt,name=src_iface,json=srcIface,proto3" json:"src_iface,omitempty"`                                // local_meta.src_iface, excat, uint
	TunnelIpv4Dst     string `protobuf:"bytes,2,opt,name=tunnel_ipv4_dst,json=tunnelIpv4Dst,proto3" json:"tunnel_ipv4_dst,omitempty"`                // hdr.outer_ipv4.dst_addr, ternary, ipv4
	TunnelIpv4DstMask uint32 `protobuf:"varint,3,opt,name=tunnel_ipv4_dst_mask,json=tunnelIpv4DstMask,proto3" json:"tunnel_ipv4_dst_mask,omitempty"` // hdr.outer_ipv4.dst_addr mask，目前先用int代替
	Teid              uint32 `protobuf:"varint,4,opt,name=teid,proto3" json:"teid,omitempty"`                                                        // local_meta.teid, ternary
	TeidMask          uint32 `protobuf:"varint,5,opt,name=teid_mask,json=teidMask,proto3" json:"teid_mask,omitempty"`                                // local_meta.teid mask,目前先用int代替
	UeAddr            string `protobuf:"bytes,6,opt,name=ue_addr,json=ueAddr,proto3" json:"ue_addr,omitempty"`                                       // local_meta.ue_addr, ternary
	UeAddrMask        uint32 `protobuf:"varint,7,opt,name=ue_addr_mask,json=ueAddrMask,proto3" json:"ue_addr_mask,omitempty"`                        //  local_meta.ue_addr mask, 目前先用int代替
	InetAddr          string `protobuf:"bytes,8,opt,name=inet_addr,json=inetAddr,proto3" json:"inet_addr,omitempty"`                                 // local_meta.inet_addr,ternary
	InetAddrMask      uint32 `protobuf:"varint,9,opt,name=inet_addr_mask,json=inetAddrMask,proto3" json:"inet_addr_mask,omitempty"`                  // local_meta.inet_addr mask, 目前先用int代替
	UeL4PortLow       uint32 `protobuf:"varint,10,opt,name=ue_l4_port_low,json=ueL4PortLow,proto3" json:"ue_l4_port_low,omitempty"`                  // local_meta.ue_l4_port, low range
	UeL4PortHigh      uint32 `protobuf:"varint,11,opt,name=ue_l4_port_high,json=ueL4PortHigh,proto3" json:"ue_l4_port_high,omitempty"`               // local_meta.ue_l4_port, high range
	InetL4PortLow     uint32 `protobuf:"varint,12,opt,name=inet_l4_port_low,json=inetL4PortLow,proto3" json:"inet_l4_port_low,omitempty"`            // local_meta.inet_l4_port, low range
	InetL4PortHigh    uint32 `protobuf:"varint,13,opt,name=inet_l4_port_high,json=inetL4PortHigh,proto3" json:"inet_l4_port_high,omitempty"`         // local_meta.inet_l4_port, high range
	Ipv4Proto         uint32 `protobuf:"varint,14,opt,name=ipv4_proto,json=ipv4Proto,proto3" json:"ipv4_proto,omitempty"`                            // hdr.ipv4.proto, ternary
	Ipv4ProtoMask     uint32 `protobuf:"varint,15,opt,name=ipv4_proto_mask,json=ipv4ProtoMask,proto3" json:"ipv4_proto_mask,omitempty"`              // hdr.ipv4.proto mask, ternary
	HasQfi            bool   `protobuf:"varint,16,opt,name=has_qfi,json=hasQfi,proto3" json:"has_qfi,omitempty"`                                     // hdr.gtpu_ext_psc.isValid(), ternary
	HasQfiMask        uint32 `protobuf:"varint,17,opt,name=has_qfi_mask,json=hasQfiMask,proto3" json:"has_qfi_mask,omitempty"`
	Qfi               uint32 `protobuf:"varint,18,opt,name=qfi,proto3" json:"qfi,omitempty"` // hdr.gtpu_ext_psc.qfi, ternary
	QfiMask           uint32 `protobuf:"varint,19,opt,name=qfi_mask,json=qfiMask,proto3" json:"qfi_mask,omitempty"`
	Priority          uint32 `protobuf:"varint,20,opt,name=priority,proto3" json:"priority,omitempty"` // 三态匹配优先级
}

func (x *PDRTableKey) Reset() {
	*x = PDRTableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDRTableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDRTableKey) ProtoMessage() {}

func (x *PDRTableKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDRTableKey.ProtoReflect.Descriptor instead.
func (*PDRTableKey) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *PDRTableKey) GetSrcIface() uint32 {
	if x != nil {
		return x.SrcIface
	}
	return 0
}

func (x *PDRTableKey) GetTunnelIpv4Dst() string {
	if x != nil {
		return x.TunnelIpv4Dst
	}
	return ""
}

func (x *PDRTableKey) GetTunnelIpv4DstMask() uint32 {
	if x != nil {
		return x.TunnelIpv4DstMask
	}
	return 0
}

func (x *PDRTableKey) GetTeid() uint32 {
	if x != nil {
		return x.Teid
	}
	return 0
}

func (x *PDRTableKey) GetTeidMask() uint32 {
	if x != nil {
		return x.TeidMask
	}
	return 0
}

func (x *PDRTableKey) GetUeAddr() string {
	if x != nil {
		return x.UeAddr
	}
	return ""
}

func (x *PDRTableKey) GetUeAddrMask() uint32 {
	if x != nil {
		return x.UeAddrMask
	}
	return 0
}

func (x *PDRTableKey) GetInetAddr() string {
	if x != nil {
		return x.InetAddr
	}
	return ""
}

func (x *PDRTableKey) GetInetAddrMask() uint32 {
	if x != nil {
		return x.InetAddrMask
	}
	return 0
}

func (x *PDRTableKey) GetUeL4PortLow() uint32 {
	if x != nil {
		return x.UeL4PortLow
	}
	return 0
}

func (x *PDRTableKey) GetUeL4PortHigh() uint32 {
	if x != nil {
		return x.UeL4PortHigh
	}
	return 0
}

func (x *PDRTableKey) GetInetL4PortLow() uint32 {
	if x != nil {
		return x.InetL4PortLow
	}
	return 0
}

func (x *PDRTableKey) GetInetL4PortHigh() uint32 {
	if x != nil {
		return x.InetL4PortHigh
	}
	return 0
}

func (x *PDRTableKey) GetIpv4Proto() uint32 {
	if x != nil {
		return x.Ipv4Proto
	}
	return 0
}

func (x *PDRTableKey) GetIpv4ProtoMask() uint32 {
	if x != nil {
		return x.Ipv4ProtoMask
	}
	return 0
}

func (x *PDRTableKey) GetHasQfi() bool {
	if x != nil {
		return x.HasQfi
	}
	return false
}

func (x *PDRTableKey) GetHasQfiMask() uint32 {
	if x != nil {
		return x.HasQfiMask
	}
	return 0
}

func (x *PDRTableKey) GetQfi() uint32 {
	if x != nil {
		return x.Qfi
	}
	return 0
}

func (x *PDRTableKey) GetQfiMask() uint32 {
	if x != nil {
		return x.QfiMask
	}
	return 0
}

func (x *PDRTableKey) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type PDRTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action      PDRTableData_ActionName                 `protobuf:"varint,1,opt,name=action,proto3,enum=PDRTableData_ActionName" json:"action,omitempty"`
	PdrAction_1 *PDRTableData_ActionSetPDRAttributes    `protobuf:"bytes,2,opt,name=pdr_action_1,json=pdrAction1,proto3" json:"pdr_action_1,omitempty"`
	PdrAction_2 *PDRTableData_ActionSetPDRAttributesQos `protobuf:"bytes,3,opt,name=pdr_action_2,json=pdrAction2,proto3" json:"pdr_action_2,omitempty"`
}

func (x *PDRTableData) Reset() {
	*x = PDRTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDRTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDRTableData) ProtoMessage() {}

func (x *PDRTableData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDRTableData.ProtoReflect.Descriptor instead.
func (*PDRTableData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *PDRTableData) GetAction() PDRTableData_ActionName {
	if x != nil {
		return x.Action
	}
	return PDRTableData_set_pdr_attributes
}

func (x *PDRTableData) GetPdrAction_1() *PDRTableData_ActionSetPDRAttributes {
	if x != nil {
		return x.PdrAction_1
	}
	return nil
}

func (x *PDRTableData) GetPdrAction_2() *PDRTableData_ActionSetPDRAttributesQos {
	if x != nil {
		return x.PdrAction_2
	}
	return nil
}

type CreatePDRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *PDRTableKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data *PDRTableData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreatePDRRequest) Reset() {
	*x = CreatePDRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePDRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePDRRequest) ProtoMessage() {}

func (x *CreatePDRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePDRRequest.ProtoReflect.Descriptor instead.
func (*CreatePDRRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePDRRequest) GetKey() *PDRTableKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreatePDRRequest) GetData() *PDRTableData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FARTableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FarId uint32 `protobuf:"varint,1,opt,name=far_id,json=farId,proto3" json:"far_id,omitempty"` //local_meta.far.id
	Fseid uint32 `protobuf:"varint,2,opt,name=fseid,proto3" json:"fseid,omitempty"`              // local_meta.fseid
}

func (x *FARTableKey) Reset() {
	*x = FARTableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FARTableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FARTableKey) ProtoMessage() {}

func (x *FARTableKey) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FARTableKey.ProtoReflect.Descriptor instead.
func (*FARTableKey) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *FARTableKey) GetFarId() uint32 {
	if x != nil {
		return x.FarId
	}
	return 0
}

func (x *FARTableKey) GetFseid() uint32 {
	if x != nil {
		return x.Fseid
	}
	return 0
}

type FARTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action      FARTableData_ActionName                     `protobuf:"varint,1,opt,name=action,proto3,enum=FARTableData_ActionName" json:"action,omitempty"`
	FarAction_1 *FARTableData_ActionLoadNormalFarAttributes `protobuf:"bytes,2,opt,name=far_action_1,json=farAction1,proto3" json:"far_action_1,omitempty"`
	FarAction_2 *FARTableData_ActionLoadTunnelFarAttributes `protobuf:"bytes,3,opt,name=far_action_2,json=farAction2,proto3" json:"far_action_2,omitempty"`
}

func (x *FARTableData) Reset() {
	*x = FARTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FARTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FARTableData) ProtoMessage() {}

func (x *FARTableData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FARTableData.ProtoReflect.Descriptor instead.
func (*FARTableData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *FARTableData) GetAction() FARTableData_ActionName {
	if x != nil {
		return x.Action
	}
	return FARTableData_load_normal_far_attributes
}

func (x *FARTableData) GetFarAction_1() *FARTableData_ActionLoadNormalFarAttributes {
	if x != nil {
		return x.FarAction_1
	}
	return nil
}

func (x *FARTableData) GetFarAction_2() *FARTableData_ActionLoadTunnelFarAttributes {
	if x != nil {
		return x.FarAction_2
	}
	return nil
}

type CreateFARRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *FARTableKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data *FARTableData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateFARRequest) Reset() {
	*x = CreateFARRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFARRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFARRequest) ProtoMessage() {}

func (x *CreateFARRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFARRequest.ProtoReflect.Descriptor instead.
func (*CreateFARRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{16}
}

func (x *CreateFARRequest) GetKey() *FARTableKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateFARRequest) GetData() *FARTableData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SrcIfLookupTableData_ActionSetSourceIface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcIface  uint32 `protobuf:"varint,1,opt,name=src_iface,json=srcIface,proto3" json:"src_iface,omitempty"`
	Direction uint32 `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *SrcIfLookupTableData_ActionSetSourceIface) Reset() {
	*x = SrcIfLookupTableData_ActionSetSourceIface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrcIfLookupTableData_ActionSetSourceIface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrcIfLookupTableData_ActionSetSourceIface) ProtoMessage() {}

func (x *SrcIfLookupTableData_ActionSetSourceIface) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrcIfLookupTableData_ActionSetSourceIface.ProtoReflect.Descriptor instead.
func (*SrcIfLookupTableData_ActionSetSourceIface) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SrcIfLookupTableData_ActionSetSourceIface) GetSrcIface() uint32 {
	if x != nil {
		return x.SrcIface
	}
	return 0
}

func (x *SrcIfLookupTableData_ActionSetSourceIface) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type RouteTableData_ActionRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcMac     string `protobuf:"bytes,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	DstMac     string `protobuf:"bytes,2,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
	EgressPort uint32 `protobuf:"varint,3,opt,name=egress_port,json=egressPort,proto3" json:"egress_port,omitempty"`
}

func (x *RouteTableData_ActionRoute) Reset() {
	*x = RouteTableData_ActionRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteTableData_ActionRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableData_ActionRoute) ProtoMessage() {}

func (x *RouteTableData_ActionRoute) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableData_ActionRoute.ProtoReflect.Descriptor instead.
func (*RouteTableData_ActionRoute) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RouteTableData_ActionRoute) GetSrcMac() string {
	if x != nil {
		return x.SrcMac
	}
	return ""
}

func (x *RouteTableData_ActionRoute) GetDstMac() string {
	if x != nil {
		return x.DstMac
	}
	return ""
}

func (x *RouteTableData_ActionRoute) GetEgressPort() uint32 {
	if x != nil {
		return x.EgressPort
	}
	return 0
}

type PDRTableData_ActionSetPDRAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdrId uint32 `protobuf:"varint,1,opt,name=pdr_id,json=pdrId,proto3" json:"pdr_id,omitempty"`
	Fseid uint32 `protobuf:"varint,2,opt,name=fseid,proto3" json:"fseid,omitempty"`
	//uint32 counter_index = ;
	FarId          uint32 `protobuf:"varint,3,opt,name=far_id,json=farId,proto3" json:"far_id,omitempty"`
	NeedsGtpuDecap bool   `protobuf:"varint,4,opt,name=needs_gtpu_decap,json=needsGtpuDecap,proto3" json:"needs_gtpu_decap,omitempty"`
}

func (x *PDRTableData_ActionSetPDRAttributes) Reset() {
	*x = PDRTableData_ActionSetPDRAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDRTableData_ActionSetPDRAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDRTableData_ActionSetPDRAttributes) ProtoMessage() {}

func (x *PDRTableData_ActionSetPDRAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDRTableData_ActionSetPDRAttributes.ProtoReflect.Descriptor instead.
func (*PDRTableData_ActionSetPDRAttributes) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{12, 0}
}

func (x *PDRTableData_ActionSetPDRAttributes) GetPdrId() uint32 {
	if x != nil {
		return x.PdrId
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributes) GetFseid() uint32 {
	if x != nil {
		return x.Fseid
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributes) GetFarId() uint32 {
	if x != nil {
		return x.FarId
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributes) GetNeedsGtpuDecap() bool {
	if x != nil {
		return x.NeedsGtpuDecap
	}
	return false
}

type PDRTableData_ActionSetPDRAttributesQos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdrId uint32 `protobuf:"varint,1,opt,name=pdr_id,json=pdrId,proto3" json:"pdr_id,omitempty"`
	Fseid uint32 `protobuf:"varint,2,opt,name=fseid,proto3" json:"fseid,omitempty"`
	//uint32 counter_index = ;
	FarId          uint32 `protobuf:"varint,3,opt,name=far_id,json=farId,proto3" json:"far_id,omitempty"`
	NeedsGtpuDecap bool   `protobuf:"varint,4,opt,name=needs_gtpu_decap,json=needsGtpuDecap,proto3" json:"needs_gtpu_decap,omitempty"`
	NeedsQfiPush   bool   `protobuf:"varint,5,opt,name=needs_qfi_push,json=needsQfiPush,proto3" json:"needs_qfi_push,omitempty"`
	Qfi            uint32 `protobuf:"varint,6,opt,name=qfi,proto3" json:"qfi,omitempty"`
}

func (x *PDRTableData_ActionSetPDRAttributesQos) Reset() {
	*x = PDRTableData_ActionSetPDRAttributesQos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDRTableData_ActionSetPDRAttributesQos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDRTableData_ActionSetPDRAttributesQos) ProtoMessage() {}

func (x *PDRTableData_ActionSetPDRAttributesQos) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDRTableData_ActionSetPDRAttributesQos.ProtoReflect.Descriptor instead.
func (*PDRTableData_ActionSetPDRAttributesQos) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{12, 1}
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetPdrId() uint32 {
	if x != nil {
		return x.PdrId
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetFseid() uint32 {
	if x != nil {
		return x.Fseid
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetFarId() uint32 {
	if x != nil {
		return x.FarId
	}
	return 0
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetNeedsGtpuDecap() bool {
	if x != nil {
		return x.NeedsGtpuDecap
	}
	return false
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetNeedsQfiPush() bool {
	if x != nil {
		return x.NeedsQfiPush
	}
	return false
}

func (x *PDRTableData_ActionSetPDRAttributesQos) GetQfi() uint32 {
	if x != nil {
		return x.Qfi
	}
	return 0
}

type FARTableData_ActionLoadNormalFarAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedsDropping bool `protobuf:"varint,1,opt,name=needs_dropping,json=needsDropping,proto3" json:"needs_dropping,omitempty"`
	NotifyCp      bool `protobuf:"varint,2,opt,name=notify_cp,json=notifyCp,proto3" json:"notify_cp,omitempty"`
}

func (x *FARTableData_ActionLoadNormalFarAttributes) Reset() {
	*x = FARTableData_ActionLoadNormalFarAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FARTableData_ActionLoadNormalFarAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FARTableData_ActionLoadNormalFarAttributes) ProtoMessage() {}

func (x *FARTableData_ActionLoadNormalFarAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FARTableData_ActionLoadNormalFarAttributes.ProtoReflect.Descriptor instead.
func (*FARTableData_ActionLoadNormalFarAttributes) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{15, 0}
}

func (x *FARTableData_ActionLoadNormalFarAttributes) GetNeedsDropping() bool {
	if x != nil {
		return x.NeedsDropping
	}
	return false
}

func (x *FARTableData_ActionLoadNormalFarAttributes) GetNotifyCp() bool {
	if x != nil {
		return x.NotifyCp
	}
	return false
}

type FARTableData_ActionLoadTunnelFarAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedsDropping  bool   `protobuf:"varint,1,opt,name=needs_dropping,json=needsDropping,proto3" json:"needs_dropping,omitempty"`
	NotifyCp       bool   `protobuf:"varint,2,opt,name=notify_cp,json=notifyCp,proto3" json:"notify_cp,omitempty"`
	NeedsBuffering bool   `protobuf:"varint,3,opt,name=needs_buffering,json=needsBuffering,proto3" json:"needs_buffering,omitempty"`
	TunnelType     uint32 `protobuf:"varint,4,opt,name=tunnel_type,json=tunnelType,proto3" json:"tunnel_type,omitempty"`
	SrcAddr        string `protobuf:"bytes,5,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr        string `protobuf:"bytes,6,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	Teid           uint32 `protobuf:"varint,7,opt,name=teid,proto3" json:"teid,omitempty"`
	L4Port         uint32 `protobuf:"varint,8,opt,name=L4Port,proto3" json:"L4Port,omitempty"`
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) Reset() {
	*x = FARTableData_ActionLoadTunnelFarAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FARTableData_ActionLoadTunnelFarAttributes) ProtoMessage() {}

func (x *FARTableData_ActionLoadTunnelFarAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FARTableData_ActionLoadTunnelFarAttributes.ProtoReflect.Descriptor instead.
func (*FARTableData_ActionLoadTunnelFarAttributes) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{15, 1}
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetNeedsDropping() bool {
	if x != nil {
		return x.NeedsDropping
	}
	return false
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetNotifyCp() bool {
	if x != nil {
		return x.NotifyCp
	}
	return false
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetNeedsBuffering() bool {
	if x != nil {
		return x.NeedsBuffering
	}
	return false
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetTunnelType() uint32 {
	if x != nil {
		return x.TunnelType
	}
	return 0
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetSrcAddr() string {
	if x != nil {
		return x.SrcAddr
	}
	return ""
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetDstAddr() string {
	if x != nil {
		return x.DstAddr
	}
	return ""
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetTeid() uint32 {
	if x != nil {
		return x.Teid
	}
	return 0
}

func (x *FARTableData_ActionLoadTunnelFarAttributes) GetL4Port() uint32 {
	if x != nil {
		return x.L4Port
	}
	return 0
}

var File_grpc_proto protoreflect.FileDescriptor

var file_grpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x26, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x13, 0x53, 0x72, 0x63,
	0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x2d, 0x0a, 0x13, 0x64,
	0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e, 0x22, 0xa5, 0x02, 0x0a, 0x14, 0x53,
	0x72, 0x63, 0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x53, 0x72, 0x63, 0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5c, 0x0a,
	0x14, 0x53, 0x72, 0x63, 0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x53, 0x72,
	0x63, 0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x66, 0x61, 0x63, 0x65, 0x52, 0x12, 0x53, 0x72, 0x63, 0x49, 0x66, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x1a, 0x51, 0x0a, 0x14, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x66, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x72, 0x63, 0x49, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22,
	0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x73, 0x65, 0x74, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x66, 0x61, 0x63, 0x65,
	0x10, 0x00, 0x22, 0x70, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x72, 0x63, 0x49,
	0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x53, 0x72, 0x63, 0x49, 0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x72, 0x63, 0x49, 0x66, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x11, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x73, 0x74,
	0x5f, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x74, 0x4d,
	0x61, 0x63, 0x22, 0x69, 0x0a, 0x12, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x1b, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0d,
	0x0a, 0x09, 0x6e, 0x6f, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x22, 0x6c, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x0d, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0b,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x48, 0x6f, 0x70, 0x49, 0x70, 0x12, 0x32, 0x0a, 0x16,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x6e, 0x65,
	0x78, 0x74, 0x48, 0x6f, 0x70, 0x49, 0x70, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e,
	0x22, 0x82, 0x02, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x0c, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x1a, 0x60, 0x0a, 0x0b, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x72, 0x63,
	0x5f, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x72, 0x63, 0x4d,
	0x61, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x17, 0x0a, 0x0a,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x10, 0x00, 0x22, 0x60, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9d, 0x05, 0x0a, 0x0b, 0x50, 0x44, 0x52, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x72, 0x63, 0x5f, 0x69,
	0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x72, 0x63, 0x49,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69,
	0x70, 0x76, 0x34, 0x5f, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x70, 0x76, 0x34, 0x44, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x14,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x64, 0x73, 0x74, 0x5f,
	0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x70, 0x76, 0x34, 0x44, 0x73, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x65, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x69, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x65, 0x69, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x65, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6e, 0x65, 0x74, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x69, 0x6e, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x23, 0x0a, 0x0e,
	0x75, 0x65, 0x5f, 0x6c, 0x34, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x77, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x65, 0x4c, 0x34, 0x50, 0x6f, 0x72, 0x74, 0x4c, 0x6f,
	0x77, 0x12, 0x25, 0x0a, 0x0f, 0x75, 0x65, 0x5f, 0x6c, 0x34, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x68, 0x69, 0x67, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x75, 0x65, 0x4c, 0x34,
	0x50, 0x6f, 0x72, 0x74, 0x48, 0x69, 0x67, 0x68, 0x12, 0x27, 0x0a, 0x10, 0x69, 0x6e, 0x65, 0x74,
	0x5f, 0x6c, 0x34, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x77, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x69, 0x6e, 0x65, 0x74, 0x4c, 0x34, 0x50, 0x6f, 0x72, 0x74, 0x4c, 0x6f,
	0x77, 0x12, 0x29, 0x0a, 0x11, 0x69, 0x6e, 0x65, 0x74, 0x5f, 0x6c, 0x34, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x69, 0x6e,
	0x65, 0x74, 0x4c, 0x34, 0x50, 0x6f, 0x72, 0x74, 0x48, 0x69, 0x67, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x70, 0x76, 0x34, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x69, 0x70, 0x76, 0x34, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x0a, 0x0f, 0x69,
	0x70, 0x76, 0x34, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x69, 0x70, 0x76, 0x34, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d,
	0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x5f, 0x71, 0x66, 0x69, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x73, 0x51, 0x66, 0x69, 0x12, 0x20, 0x0a, 0x0c,
	0x68, 0x61, 0x73, 0x5f, 0x71, 0x66, 0x69, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x51, 0x66, 0x69, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x71, 0x66, 0x69, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x66, 0x69,
	0x12, 0x19, 0x0a, 0x08, 0x71, 0x66, 0x69, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x13, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x71, 0x66, 0x69, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0xe2, 0x04, 0x0a, 0x0c, 0x50, 0x44, 0x52, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x50, 0x44, 0x52, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0c, 0x70, 0x64,
	0x72, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x50, 0x44, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x50, 0x44, 0x52, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x70, 0x64, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x31, 0x12, 0x49, 0x0a, 0x0c, 0x70, 0x64, 0x72, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x50, 0x44, 0x52, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x50, 0x44, 0x52, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x51, 0x6f,
	0x73, 0x52, 0x0a, 0x70, 0x64, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x1a, 0x86, 0x01,
	0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x50, 0x44, 0x52, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x64, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x64, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x73, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x66, 0x73, 0x65, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x61, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x6e, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x67, 0x74, 0x70, 0x75, 0x5f, 0x64, 0x65, 0x63, 0x61, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x47, 0x74, 0x70,
	0x75, 0x44, 0x65, 0x63, 0x61, 0x70, 0x1a, 0xc1, 0x01, 0x0a, 0x19, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x74, 0x50, 0x44, 0x52, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x51, 0x6f, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x64, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x64, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x73, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x73, 0x65, 0x69,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x66, 0x61, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x65, 0x65, 0x64,
	0x73, 0x5f, 0x67, 0x74, 0x70, 0x75, 0x5f, 0x64, 0x65, 0x63, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x47, 0x74, 0x70, 0x75, 0x44, 0x65, 0x63,
	0x61, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x71, 0x66, 0x69, 0x5f,
	0x70, 0x75, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6e, 0x65, 0x65, 0x64,
	0x73, 0x51, 0x66, 0x69, 0x50, 0x75, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x66, 0x69, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x71, 0x66, 0x69, 0x22, 0x40, 0x0a, 0x0a, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x73, 0x65, 0x74, 0x5f,
	0x70, 0x64, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x73, 0x65, 0x74, 0x5f, 0x70, 0x64, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x71, 0x6f, 0x73, 0x10, 0x01, 0x22, 0x55, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x44, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x50, 0x44, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x50, 0x44, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x0b, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x66, 0x61, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x73, 0x65,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x73, 0x65, 0x69, 0x64, 0x22,
	0xa3, 0x05, 0x0a, 0x0c, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x30, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x0c, 0x66, 0x61, 0x72, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x46, 0x41, 0x52, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f,
	0x61, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x46, 0x61, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x66, 0x61, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x31, 0x12, 0x4d, 0x0a, 0x0c, 0x66, 0x61, 0x72, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x61,
	0x64, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x61, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x66, 0x61, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32,
	0x1a, 0x63, 0x0a, 0x1d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x46, 0x61, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x73,
	0x44, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x5f, 0x63, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x43, 0x70, 0x1a, 0x8f, 0x02, 0x0a, 0x1d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x6f, 0x61, 0x64, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x61, 0x72, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73,
	0x5f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x70, 0x12, 0x27, 0x0a, 0x0f, 0x6e,
	0x65, 0x65, 0x64, 0x73, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x42, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x65, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x4c, 0x34, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x4c, 0x34, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x4c, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x66, 0x61, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x66, 0x61, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x10, 0x01, 0x22, 0x55, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x41, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x41, 0x52, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xbb, 0x03, 0x0a,
	0x0b, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x08,
	0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x72, 0x63, 0x49, 0x66, 0x61, 0x63, 0x65, 0x4c,
	0x6f, 0x6f, 0x6b, 0x12, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x72, 0x63, 0x49,
	0x66, 0x4c, 0x6f, 0x6f, 0x6b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x44, 0x52, 0x12, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x44, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x44, 0x52, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x50, 0x44, 0x52, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x41, 0x52, 0x12, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x41, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x41, 0x52, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x41, 0x52, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x3b, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData = file_grpc_proto_rawDesc
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_rawDescData)
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_grpc_proto_goTypes = []interface{}{
	(SrcIfLookupTableData_ActionName)(0),               // 0: SrcIfLookupTableData.ActionName
	(MyStationTableData_ActionName)(0),                 // 1: MyStationTableData.ActionName
	(RouteTableData_ActionName)(0),                     // 2: RouteTableData.ActionName
	(PDRTableData_ActionName)(0),                       // 3: PDRTableData.ActionName
	(FARTableData_ActionName)(0),                       // 4: FARTableData.ActionName
	(*Request)(nil),                                    // 5: Request
	(*Response)(nil),                                   // 6: Response
	(*SrcIfLookupTableKey)(nil),                        // 7: SrcIfLookupTableKey
	(*SrcIfLookupTableData)(nil),                       // 8: SrcIfLookupTableData
	(*CreateSrcIfLookTableRequest)(nil),                // 9: CreateSrcIfLookTableRequest
	(*MyStationTableKey)(nil),                          // 10: MyStationTableKey
	(*MyStationTableData)(nil),                         // 11: MyStationTableData
	(*CreateMyStationTableRequest)(nil),                // 12: CreateMyStationTableRequest
	(*RouteTableKey)(nil),                              // 13: RouteTableKey
	(*RouteTableData)(nil),                             // 14: RouteTableData
	(*CreateRouteTableRequest)(nil),                    // 15: CreateRouteTableRequest
	(*PDRTableKey)(nil),                                // 16: PDRTableKey
	(*PDRTableData)(nil),                               // 17: PDRTableData
	(*CreatePDRRequest)(nil),                           // 18: CreatePDRRequest
	(*FARTableKey)(nil),                                // 19: FARTableKey
	(*FARTableData)(nil),                               // 20: FARTableData
	(*CreateFARRequest)(nil),                           // 21: CreateFARRequest
	(*SrcIfLookupTableData_ActionSetSourceIface)(nil),  // 22: SrcIfLookupTableData.ActionSetSourceIface
	(*RouteTableData_ActionRoute)(nil),                 // 23: RouteTableData.ActionRoute
	(*PDRTableData_ActionSetPDRAttributes)(nil),        // 24: PDRTableData.ActionSetPDRAttributes
	(*PDRTableData_ActionSetPDRAttributesQos)(nil),     // 25: PDRTableData.ActionSetPDRAttributesQos
	(*FARTableData_ActionLoadNormalFarAttributes)(nil), // 26: FARTableData.ActionLoadNormalFarAttributes
	(*FARTableData_ActionLoadTunnelFarAttributes)(nil), // 27: FARTableData.ActionLoadTunnelFarAttributes
}
var file_grpc_proto_depIdxs = []int32{
	0,  // 0: SrcIfLookupTableData.action:type_name -> SrcIfLookupTableData.ActionName
	22, // 1: SrcIfLookupTableData.SrcIfLookup_action_1:type_name -> SrcIfLookupTableData.ActionSetSourceIface
	7,  // 2: CreateSrcIfLookTableRequest.key:type_name -> SrcIfLookupTableKey
	8,  // 3: CreateSrcIfLookTableRequest.data:type_name -> SrcIfLookupTableData
	1,  // 4: MyStationTableData.action:type_name -> MyStationTableData.ActionName
	10, // 5: CreateMyStationTableRequest.key:type_name -> MyStationTableKey
	11, // 6: CreateMyStationTableRequest.data:type_name -> MyStationTableData
	2,  // 7: RouteTableData.action:type_name -> RouteTableData.ActionName
	23, // 8: RouteTableData.route_action_1:type_name -> RouteTableData.ActionRoute
	13, // 9: CreateRouteTableRequest.key:type_name -> RouteTableKey
	14, // 10: CreateRouteTableRequest.data:type_name -> RouteTableData
	3,  // 11: PDRTableData.action:type_name -> PDRTableData.ActionName
	24, // 12: PDRTableData.pdr_action_1:type_name -> PDRTableData.ActionSetPDRAttributes
	25, // 13: PDRTableData.pdr_action_2:type_name -> PDRTableData.ActionSetPDRAttributesQos
	16, // 14: CreatePDRRequest.key:type_name -> PDRTableKey
	17, // 15: CreatePDRRequest.data:type_name -> PDRTableData
	4,  // 16: FARTableData.action:type_name -> FARTableData.ActionName
	26, // 17: FARTableData.far_action_1:type_name -> FARTableData.ActionLoadNormalFarAttributes
	27, // 18: FARTableData.far_action_2:type_name -> FARTableData.ActionLoadTunnelFarAttributes
	19, // 19: CreateFARRequest.key:type_name -> FARTableKey
	20, // 20: CreateFARRequest.data:type_name -> FARTableData
	5,  // 21: GrpcService.SayHello:input_type -> Request
	9,  // 22: GrpcService.CreateSrcIfaceLook:input_type -> CreateSrcIfLookTableRequest
	12, // 23: GrpcService.CreateMyStation:input_type -> CreateMyStationTableRequest
	15, // 24: GrpcService.CreateRoute:input_type -> CreateRouteTableRequest
	18, // 25: GrpcService.CreatePDR:input_type -> CreatePDRRequest
	5,  // 26: GrpcService.UpdatePDR:input_type -> Request
	5,  // 27: GrpcService.RemovePDR:input_type -> Request
	21, // 28: GrpcService.CreateFAR:input_type -> CreateFARRequest
	5,  // 29: GrpcService.UpdateFAR:input_type -> Request
	5,  // 30: GrpcService.RemoveFAR:input_type -> Request
	6,  // 31: GrpcService.SayHello:output_type -> Response
	6,  // 32: GrpcService.CreateSrcIfaceLook:output_type -> Response
	6,  // 33: GrpcService.CreateMyStation:output_type -> Response
	6,  // 34: GrpcService.CreateRoute:output_type -> Response
	6,  // 35: GrpcService.CreatePDR:output_type -> Response
	6,  // 36: GrpcService.UpdatePDR:output_type -> Response
	6,  // 37: GrpcService.RemovePDR:output_type -> Response
	6,  // 38: GrpcService.CreateFAR:output_type -> Response
	6,  // 39: GrpcService.UpdateFAR:output_type -> Response
	6,  // 40: GrpcService.RemoveFAR:output_type -> Response
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrcIfLookupTableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrcIfLookupTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSrcIfLookTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStationTableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStationTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMyStationTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteTableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouteTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDRTableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDRTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePDRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FARTableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FARTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFARRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrcIfLookupTableData_ActionSetSourceIface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteTableData_ActionRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDRTableData_ActionSetPDRAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDRTableData_ActionSetPDRAttributesQos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FARTableData_ActionLoadNormalFarAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FARTableData_ActionLoadTunnelFarAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		EnumInfos:         file_grpc_proto_enumTypes,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_rawDesc = nil
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
